### ISSUE TITLE
Error Handling for Background Image Selection

### ISSUE THREAD

**Issue by jeturgavli** [jeturgavli/Quote-Image-Generator-for-Instagram#4]
When the user inputs an invalid background image name, the program does not handle the error gracefully and crashes.

### Steps to Reproduce:
1. Run the program.
2. When prompted to "Choose Background:", enter an invalid image name that does not exist in the Backgrounds directory.
3. Observe the crash.

The program should notify the user that the entered background image name is invalid and prompt for a valid one, rather than crashing.

If anyone is interested in fixing this issue, I would greatly appreciate your help. 
Thank you! ❤

**Comment by morenzorafael** [comment]
Hi, I would like to try to fix this issue! Could you assign it to me please?

**Comment by jeturgavli** [comment]
@morenzorafael 
Thank you for taking on this task!

**Comment by jeturgavli** [comment]
Hey @morenzorafael, 
Could you please let me know how much time it will take to complete this fix?
