### ISSUE TITLE
Random image generator

### ISSUE THREAD

**Issue by Bashamega** [jeturgavli/Quote-Image-Generator-for-Instagram#7]
Hello:)
My idea is to add an option to generate a random picture. So if the user wrote the word `random` the python program will randomly choose an image.

I would like to work on that.

**Comment by jeturgavli** [comment]
Hi @Bashamega 

Thank you for your interest in contributing to the project and for the great idea to add an option to generate a random picture! I think this feature would be a fantastic addition.

Please go ahead and start working on it 😎😸😻
